# Generated by Django 4.1.4 on 2022-12-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='invite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='manager',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='status',
            field=models.CharField(choices=[(1, 'first'), (2, 'second'), (3, 'third')], default=1, max_length=1),
        ),
    ]
